[[proxy]]
backend = "http://localhost:8081/" # Address to proxy requests to
ws = false                                # Use WebSocket for this proxy
insecure = false                          # Disable certificate validation
no_system_proxy = false                   # Disable system proxy
rewrite = "/api"                          # Strip the given prefix off paths
no_redirect = false                       # Disable following redirects of proxy responses
