CREATE TABLE authorization_tokens (
	id VARCHAR(32) PRIMARY KEY NOT NULL,

	token VARCHAR(32) UNIQUE NOT NULL,
	user_id INTEGER NOT NULL REFERENCES users (id),

	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
