INSERT INTO mailing_groups (name, email) VALUES
	('Baza Wiedzy', 'BazaWiedzy@confilogi.com'),
	('Biuro AppRoll', 'biuro-app-roll@confilogi.com'),
	('CC', 'cc@confilogi.com'),
	('Confilogi Awizacje Szyszkowa', 'awizacje.szyszkowa@confilogi.com'),
	('Confilogi BGP1 Team', 'bgp1@confilogi.com'),
	('Confilogi BGP2 Team', 'bgp2@confilogi.com'),
	('Confilogi Centrum Innowacji', 'CentrumInnowacji@confilogi.com'),
	('Confilogi CEO Team', 'TeamZarzad@confilogi.com'),
	('Confilogi Claude Notifications', 'claude@confilogi.com'),
	('Confilogi CZ ekstra Team', 'czekstra@confilogi.com'),
	('Confilogi CZP1 Team', 'czp1@confilogi.com'),
	('Confilogi CZP2 Team', 'czp2@confilogi.com'),
	('Confilogi Development Team', 'DevelopmentTeam@confilogi.com'),
	('Confilogi Dział Graficzny', 'DziaGraficzny@confilogi.com'),
	('Confilogi Dział Legal', 'legal@confilogi.com'),
	('Confilogi Dział Marketingu', 'ConfilogiDzialMarketingu@confilogi.com'),
	('Confilogi Dział WEB', 'DziaWEB@confilogi.com'),
	('Confilogi HRP1 Team', 'HRP1@confilogi.com'),
	('Confilogi Kampanie Marketingowe', 'kampanie.marketingowe@confilogi.com'),
	('Confilogi Logistic Notification', 'logistic_notification@confilogi.com'),
	('Confilogi Logistyka', 'logistyka@confilogi.com'),
	('Confilogi Managers', 'managerpl@confilogi.com'),
	('Confilogi Marketing Team', 'TeamMarketing@confilogi.com'),
	('Confilogi PLBF', 'PLBF@confilogi.com'),
	('Confilogi PLP1 Team', 'plp1@confilogi.com'),
	('Confilogi PLP2 Team', 'plp2@confilogi.com'),
	('Confilogi PLP3 Team', 'plp3@confilogi.com'),
	('Confilogi PLP4 Team', 'plp4@confilogi.com'),
	('Confilogi PLPV Team', 'PLPV@confilogi.com'),
	('Confilogi PLRR', 'PLRR@confilogi.com'),
	('Confilogi Raporty HR', 'RaportyHR@confilogi.com'),
	('Confilogi Raporty PLP2', 'RaportyPLP2@confilogi.com'),
	('Confilogi Raporty PLP3', 'RaportyPLP3@confilogi.com'),
	('Confilogi Raporty PLP4', 'RaportyPLP4@confilogi.com'),
	('Confilogi Raporty PLRR', 'RaportyPLRR@confilogi.com'),
	('Confilogi Raporty SK', 'raportysk@confilogi.com'),
	('Confilogi Return HR', 'returnhr@confilogi.com'),
	('Confilogi Return RS', 'returnrs@confilogi.com'),
	('Confilogi SIP1 Team', 'sip1@confilogi.com'),
	('Confilogi SKP1 Team', 'skp1@confilogi.com'),
	('Confilogi SKP2 Team', 'skp2@confilogi.com'),
	('Confilogi SKP3 Team', 'SKP3@confilogi.com'),
	('Confilogi Support', 'support@confilogi.com'),
	('Confilogi Szkolenia', 'szkolenia@confilogi.com'),
	('Confilogi Testy Reklam', 'Testyreklam@confilogi.com'),
	('Confilogi Zlecenia Kreacja', 'ZleceniaKreacja@confilogi.com'),
	('CZ-SK Dyrektorzy', 'CZ-SKDyrektorzy@confilogi.com'),
	('CZ-SK Managers', 'CZ-SKManagers@confilogi.com'),
	('CZBF', 'czbf@confilogi.com'),
	('Cznet', 'cznet@confilogi.com'),
	('Dane_Do_Raportow', 'Dane_Do_Raportow@confilogi.com'),
	('DD-Dominik Dziedzic', 'DD-DominikDziedzic@confilogi.com'),
	('Dominika- Patryk', 'Dominika-Patryk@confilogi.com'),
	('dyzurIT', 'dyzurIT@confilogi.com'),
	('Dział Wydań Bieżących', 'DziaWydaBiecych@confilogi.com'),
	('Emisje', 'Emisje@confilogi.com'),
	('Emisje.V2', 'Emisje.V2@confilogi.com'),
	('Ernest- Patryk', 'Ernest-Patryk@confilogi.com'),
	('Extrakasa', 'extrakasa@confilogi.com'),
	('Flota Rabarbarmedia', 'flota@rabarbarmedia.com'),
	('Innowacje', 'Innowacje@confilogi.com'),
	('IT', 'IT@confilogi.com'),
	('IT Support', 'ITSupport@confilogi.com'),
	('Jan-Patryk', 'Jan-Patryk@confilogi.com'),
	('Jira - Kadry', 'jira.kadry@confilogi.com'),
	('Kacper- Patryk', 'Kacper-Patryk@confilogi.com'),
	('Kadry', 'kadry@confilogi.com'),
	('kartacoachingowaplp1', 'kartacoachingowaplp1@confilogi.com'),
	('KartaCoachingowaPLP2', 'kartacoachingowaplp2@confilogi.com'),
	('Kasia-Patryk', 'Kasia-Patryk@confilogi.com'),
	('Krzysztof- Patryk', 'Krzysztof-Patryk@confilogi.com'),
	('Magazyn Centralny', 'MagazynCentralny@confilogi.com'),
	('Marcin-Patryk', 'Marcin-Patryk@confilogi.com'),
	('Marketing', 'marketing@confilogi.com'),
	('Marketing Rejestracja_Czasu_Pracy', 'MarketingRejestracja_Czasu_Pracy@confilogi.com'),
	('Michał-Patryk Support IT', 'Micha-PatrykSupportIT@confilogi.com'),
	('Moje', 'Moje@confilogi.com'),
	('Odsłuchy BG', 'odsluchybg@confilogi.com'),
	('Odsłuchy CZ', 'odsluchycz@confilogi.com'),
	('Odsłuchy HR', 'odsluchyhr@confilogi.com'),
	('Odsłuchy PL', 'odsluchypl@confilogi.com'),
	('Odsłuchy RO', 'odsluchyro@confilogi.com'),
	('Odsłuchy SK', 'odsluchysk@confilogi.com'),
	('PLAK', 'plak@confilogi.com'),
	('PLNET', 'plnet@confilogi.com'),
	('Plreturn', 'plreturn@confilogi.com'),
	('Produkty i kodowanie', 'Produktyikodowanie@confilogi.com'),
	('QC.KARTA', 'qc.karta@confilogi.com'),
	('qckarta2@confilogi.com', 'qckarta2@confilogi.com'),
	('Raporty CZ', 'raportycz@confilogi.com'),
	('RaportyRO', 'RaportyRO@confilogi.com'),
	('Research', 'Research@confilogi.com'),
	('Return BG', 'returnbg@confilogi.com'),
	('Return CZ', 'returncz@confilogi.com'),
	('Return PL', 'returnpl@confilogi.com'),
	('Return RO', 'returnro@confilogi.com'),
	('Return SI', 'returnsi@confilogi.com'),
	('Return SK', 'returnsk@confilogi.com'),
	('ROP1', 'rop1@confilogi.com'),
	('Rynek Online', 'RynekOnline@confilogi.com'),
	('Rynki_Formaty_NR_Telefonow', 'Rynki_Formaty_NR_Telefonow@confilogi.com'),
	('S.directors', 's.directors@confilogi.com'),
	('Sales Director', 'director@confilogi.com'),
	('SK EXTRA', 'skextra@confilogi.com'),
	('Smsnotification', 'smsnotification@confilogi.com'),
	('Statystyki', 'statystyki@confilogi.com'),
	('Support IT', 'SupportIT@confilogi.com'),
	('Sylwia- Patryk', 'Sylwia-Patryk@confilogi.com'),
	('Testy PLP1', 'testy_plp1@confilogi.com'),
	('TLPLP1', 'TLPLP1@confilogi.com'),
	('TrenerzyCZ', 'trenerzycz@confilogi.com'),
	('TS/SV CZ', 'tlsvcz@confilogi.com'),
	('VMS LEADS', 'VMSLEADS@confilogi.com'),
	('Wysyłka', 'wysylka@confilogi.com'),
	('Wysyłka / Magazyn', 'WysykaMagazyn@confilogi.com'),
	('wysyłka CZ SK HU', 'wysylka.cz-sk-hu@confilogi.com'),
	('WysyłkaEU', 'WysykaEU@confilogi.com'),
	('WysyłkaPL', 'WysykaPL1@confilogi.com');
