CREATE TABLE authorization_tokens (
	id SERIAL PRIMARY KEY,

	token VARCHAR(64) UNIQUE NOT NULL,
	user_id INTEGER NOT NULL REFERENCES users (id),

	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
