CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	ad_id INTEGER DEFAULT NULL UNIQUE,
	full_name VARCHAR(64) NOT NULL,
	email VARCHAR(64) NOT NULL UNIQUE,
	password VARCHAR(64) NOT NULL,
	job_title_id INTEGER NOT NULL REFERENCES job_titles (id)
);
