[package]
name = "connector"
version = "0.1.0"
edition = "2024"

[features]
default = []
server-side = ["axum"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }

axum = { version = "0.8.4", optional = true, default-features = false, features = ["json"] }
